version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-follow-up-skills-test-v2
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html
      - app-vendor:/var/www/html/vendor
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - mydb

  mydb:
    image: mysql:5.7.24
    container_name: laravel-follow-up-skills-db
    restart: unless-stopped
    environment:
      # this command is required to connect api from other container to mysql
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
      MYSQL_DATABASE: laravel-follow-up-skills-db
      #MYSQL_USER: homestead
      #MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

    volumes:
      - task-db-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - laravel

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:apache
    restart: always
    depends_on:
      - mydb
    environment:
      PMA_HOST: mydb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 8002:80
    networks:
      - laravel

volumes:
  task-db-data:
  app-vendor:

networks:
  laravel:
    driver: bridge